version: "3.7"
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /var/lib/postgresql/data
        volumes:
            - postgres-test-data:/var/lib/postgresql/data
            - ./init-db:/docker-entrypoint-initdb.d
        ports:
            - "5432:5432"
        networks:
            - pg-network
    pgadmin:
        image: dpage/pgadmin4:4.18
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: test@postgres
            PGADMIN_DEFAULT_PASSWORD: postgres
            PGADMIN_LISTEN_PORT: 80
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        ports:
            - "5433:80"
        networks:
            - pg-network
        depends_on:
            - db
#    api:
#        build: .
#        ports:
#            - 8080:8080
#            - 5005:5005
#        depends_on:
#            - db
#        environment:
#            JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
#        networks:
#            - pg-network

volumes:
    postgres-test-data: {}
    pgadmin-data: {}
networks:
    pg-network:
        driver: bridge